---
# GP3 StorageClass - Default for KubeStock
# Used for PostgreSQL StatefulSets and other persistent workloads
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer  # Creates volume in same AZ as pod
parameters:
  type: gp3
  fsType: ext4
  # GP3 defaults: 3000 IOPS, 125 MB/s throughput
  # For course project, defaults are sufficient
reclaimPolicy: Delete
allowVolumeExpansion: false
---
# GP2 StorageClass - Legacy (optional, for compatibility)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: false
